###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username": "username11",
  "email": "iusername11@gmail.com",
  "password": "12345611",
  "name": "user11"
}

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "auth":"username10",
  "password": "12345610"
}

###
GET http://localhost:8000/users

###
GET http://localhost:8000/ping