###
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "username3",
  "email": "iusername3@gmail.com",
  "password": "1234563",
  "name": "user3"
}

###
GET http://localhost:8000/auth/login?auth=some_username&password=somepassword

###
GET http://localhost:8000/users

###
GET http://localhost:8000/ping