###
POST http://localhost:8000/users
Content-Type: application/json

{
  "username": "some_username",
  "email": "some_email@gmail.com",
  "password": "somepassword",
  "name": "somenamehere"
}

###
GET http://localhost:8000/auth/login?auth=some_username&password=somepasswor

###
GET http://localhost:8000/users

###
GET http://localhost:8000/ping